### ISSUE TITLE
HTTP 404 when doing a query to yahoo

### ISSUE THREAD

**Issue by bjosun** [JECSand/yahoofinancials#157]
I get this error:
lib/python3.8/site-packages/yahoofinancials/etl.py", line 205, in _request_handler
    raise ManagedException("Server replied with server error code, HTTP " + str(response.status_code) +
yahoofinancials.etl.ManagedException: Server replied with server error code, HTTP 404 code while opening the url: https://query1.finance.yahoo.com/v6/finance/quoteSummary/husq-b.st?modules=defaultKeyStatistics&formatted=False&lang=en-US&region=US&corsDomain=finance.yahoo.com

Seems to be an issue with this:
elif tech_type != '' and statement_type != 'history':
                r_map = get_request_config(tech_type, REQUEST_MAP)
                try:
                    re_data = self._get_historical_data(YAHOO_URL, r_map, tech_type, statement_type)
                except KeyError:
                    re_data = None
                dict_ent = {up_ticker: re_data}

**Comment by micksulley** [comment]
I think I am hitting the same problem.  I run
```
>>> from yahoofinancials import YahooFinancials
>>> data = YahooFinancials('VOD.L').get_stock_price_data()
```
and get the error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mick/.local/lib/python3.10/site-packages/yahoofinancials/yf.py", line 99, in get_stock_price_data
    return self.get_clean_data(self.get_stock_tech_data('price'), 'price')
  File "/home/mick/.local/lib/python3.10/site-packages/yahoofinancials/etl.py", line 591, in get_stock_tech_data
    return self.get_stock_data(tech_type=tech_type)
  File "/home/mick/.local/lib/python3.10/site-packages/yahoofinancials/etl.py", line 561, in get_stock_data
    dict_ent = self._create_dict_ent(self.ticker, statement_type, tech_type, report_name, hist_obj)
  File "/home/mick/.local/lib/python3.10/site-packages/yahoofinancials/etl.py", line 517, in _create_dict_ent
    re_data = self._get_historical_data(YAHOO_URL, r_map, tech_type, statement_type)
  File "/home/mick/.local/lib/python3.10/site-packages/yahoofinancials/etl.py", line 244, in _get_historical_data
    self._request_handler(url, config.get("response_field"))
  File "/home/mick/.local/lib/python3.10/site-packages/yahoofinancials/etl.py", line 205, in _request_handler
    raise ManagedException("Server replied with server error code, HTTP " + str(response.status_code) +
yahoofinancials.etl.ManagedException: Server replied with server error code, HTTP 404 code while opening the url: https://query1.finance.yahoo.com/v6/finance/quoteSummary/vod.l?modules=price&formatted=False&lang=en-US&region=US&corsDomain=finance.yahoo.com
```

**Comment by JECSand** [comment]
@micksulley @bjosun Thank you for raising this issue. I’m completely slammed at work right now, however I can dedicate sometime this week towards solving this.

**Comment by valankar** [comment]
Just FYI, other Python libraries are having the same issue:

https://github.com/dpguthrie/yahooquery/issues/224
https://github.com/ranaroussi/yfinance/issues/1729

**Comment by tonyb-ludicrousSpeed** [comment]
get_financial_stmts functions as expected. The other functions throw a 404 exception as others have mentioned. I noticed that the python requests is also having issues with finance.yahoo.com. A get() request to https://finance.yahoo.com/quote/AAPL (or any other ticker) will work fine; able to scrape quote data. But a get() request to https://finance.yahoo.com/quote/AAPL/financials, or https://finance.yahoo.com/quote/AAPL/cash-flow, etc. throws the 404 error. Even though I can copy/paste the url string from the request object in the python debug window to a browser and it opens fine.

**Comment by JECSand** [comment]
Ok, I figured out a way to do this and released a fixed in v1.17. I tested it using IPs from several different countries and it seems to be working fine now. Closing this issue.

**Comment by lukaszdrukasz** [comment]
Still not working here :( My IP is from Poland, but it doesn't work for me even when using US-based proxies. The getcrumb URL returns 0 bytes, when I open it in a "real" browser, it does return a crumb string.

I'm happy to do even extensive testing. Please, let me know if there's something I should try.

**Comment by Edison0019** [comment]
Updating the package version fixed the issue. Thank you very much @JECSand !
